apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: AGENT_NAME
  namespace: NAMESPACE
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: AGENT_NAME
  service:
    port: 8000
    targetPort: 8000
  analysis:
    interval: 30s
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 30s
      - name: request-duration
        thresholdRange:
          max: 2000
        interval: 30s
