apiVersion: v1
kind: Service
metadata:
  name: {{ include "recif.fullname" . }}-api
  labels:
    {{- include "recif.componentLabels" (dict "Root" . "Component" "api") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "recif.componentSelectorLabels" (dict "Root" . "Component" "api") | nindent 4 }}
